### ISSUE TITLE
GSIBclim subdirectories

### ISSUE THREAD

**Issue by rtodling** [GEOS-ESM/gsibclim#17]
Matt,

Thanks for renaming the directory. 

Now, is it also possible to rename the subdirectory inside source to be gsibec (lower case)?

src/gsibclim -> src/gsibec

?

**Comment by rtodling** [comment]
Perhaps before you do anything. I know that I can simply rename the sub-dir when I checkout GSIbec and add/commit back. Would that be the same as you renaming internally in the repo? Something tells me that the answer is likely no. If I do it by hand from my workday and re-commit, will I retain the history on the files in the subdirectory? If yes, then I can do it by hand and you don't need to worry about this Issue - we could close it. 

Please let me know.

**Comment by mathomp4** [comment]
@rtodling Yes, you can change the name of the directory (aka `git mv`), commit and push, and git will retain the history. Sometimes GitHub gets a bit confused with file renames, but they've gotten a lot better at it recently!

**Comment by rtodling** [comment]
So I do a "git mv" - not a mv, in my local dir?

**Comment by mathomp4** [comment]
> So I do a "git mv" - not a mv, in my local dir?

either/or in truth. `git mv foo bar` is equivalent to doing a `mv foo bar` and a `git add` step after it to stage it. Sort of an "all in one" for moving files with git.

But if you want to try the rename first and make sure all is working before staging for commit, then do the two-step process.

**Comment by rtodling** [comment]
I was able to do the git mv ... I have thinks in a branch - I need to make other changes for all to compile properly under the name change. I should have a PR submitted later today - I hope.

**Comment by rtodling** [comment]
All works on this. I am closing this issue - thank you.
