### ISSUE TITLE
ak/bk need to come from JEDI

### ISSUE THREAD

**Issue by rtodling** [GEOS-ESM/gsibclim#28]
A present 1.0.5 (and earlier) has gsibec creating ak/bk - using set_eta. This needs to change so that JEDI/SABER pass ak/bk down to JEDI - avoid multiple locations of ak/bk definition.

From FV3, I see that geom carries ak/bk;
I also see that geometry is available in the create of GSI_Covariance.h  but it's not in GSI_grid.h

If I want to get ak/bk from the fg geometry,  is it the right think to do for me to pass the geom down to grid create?

**Comment by danholdaway** [comment]
This might need some thought actually. You can't pass the Geometry down to Fortran because the geometry is specific to a particular model. We need to add some accessor functions to the Geometry class that will provide akbk as generic arrays. I can take a look at that.

**Comment by rtodling** [comment]
Yes, I sort of realize that ... I was a little crude in my layout of the idea. But thinking  a little more, I think the easiest thing is for GSIbec to read the akbk file that FV3 is reading. The fact is that the global GSI is a hybrid (or sigma) pressure coordinate based system, its vertical grid is defined by a set of ak/bk and possibly ck coefficients. 

This is still tied up to a model specific, but GSIbec is not a general error covariance model. 

At least w/ this (ie. reading ak/bk from files) we guarantee to have only a single place where ak/bk comes from. As we presently have it, the model defines them in one way, and gsibec in another .... At present, anyone wanting to use GSIbec - adapting to its limitations - would have to edit GSIbec to provide its own set of ak/bk/ck.

**Comment by rtodling** [comment]
Done. This is included in version 1.0.6 (read same files that FV3 reads).
