### ISSUE TITLE
Bug in gsimod.F90

### ISSUE THREAD

**Issue by benjaminmenetrier** [GEOS-ESM/gsibclim#36]
Line 642 of `gsi/gsimod.F90`, the first argument of the call to `general_deter_subdomain_withLayout` should be `npx` instead of `npe`.

With this bugfix, SABER tests using GSI pass in debug mode. Without it they crash (but run fine in release mode...).

I have a branch ready for the bugfix, but I don't have the right to push it on this repo.

**Comment by benjaminmenetrier** [comment]
Pinging @rtodling and @danholdaway.

**Comment by danholdaway** [comment]
@benjaminmenetrier can you fork the repo and make a PR from the fork to the base?

**Comment by benjaminmenetrier** [comment]
Will do.

**Comment by rtodling** [comment]
This has been resolved - no in 1.1.1 (and 1.1.2).
