### ISSUE TITLE
Wrong module for kinds

### ISSUE THREAD

**Issue by benjaminmenetrier** [GEOS-ESM/gsibclim#7]
I noticed a bug l. 25 in `src/gsibclim/gsi/outgrads1.f90`:
https://github.com/GEOS-ESM/gsibclim/blob/b34379704f7e48119607ad9b86b148d29e2293e6/src/gsibclim/gsi/outgrads1.f90#L25
The module should be `m_kinds` instead `kinds`.

Without this change, the code does not compile.

**Comment by rtodling** [comment]
Fixed
